// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PersonelPortal.Data;

#nullable disable

namespace PersonelPortal.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251222204526_SeedPersoneller")]
    partial class SeedPersoneller
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PersonelPortal.Models.Personel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AdSoyad")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("Birim")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("Telefon")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Unvan")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.HasKey("Id");

                    b.ToTable("Personeller");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AdSoyad = "Samet Becene",
                            Birim = "Donanım Şube",
                            Telefon = "0537 279 2807",
                            Unvan = "Teknik Destek Uzmanı"
                        },
                        new
                        {
                            Id = 2,
                            AdSoyad = "Çağrı Arısoy",
                            Birim = "Yazılım Geliştirme Şubesi",
                            Telefon = "0500 111 11 11",
                            Unvan = "Yazılımcı"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
